#import "BurnEffect.h"
#import "AOESpriteTrapEffect.h"
#import "RangeBoostEffect.h"
#import "DamageBoostEffect.h"
#import "SpeedBoostEffect.h"
#import "SleepEffect.h"
#import "PoisonEffect.h"
#import "NitrousEffect.h"