//
//  TextureLibrary.h
//  ChemTD
//
//  Created by Eric Lanz on 5/27/10.
//  Copyright 2010 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "GameFieldScene.h"

#define TOWERTEXTURE_SECTIONSTART 0
#define TOWERTEXTURE_HYDROGEN 0
#define TOWERTEXTURE_OXYGEN 1
#define TOWERTEXTURE_NITROGEN 2
#define TOWERTEXTURE_WATER 3
#define TOWERTEXTURE_ACETYLENE 4
#define TOWERTEXTURE_AMMONIA 5
#define TOWERTEXTURE_ASPIRIN 6
#define TOWERTEXTURE_BAKINGSODA 7
#define TOWERTEXTURE_BLEACH 8
#define TOWERTEXTURE_CAFFEINE 9
#define TOWERTEXTURE_CAPSAICIN 10
#define TOWERTEXTURE_CARBON 11
#define TOWERTEXTURE_CARBONDIOXIDE 12
#define TOWERTEXTURE_CARBONMONOXIDE 13
#define TOWERTEXTURE_CHLORINE 14
#define TOWERTEXTURE_CHLOROFORM 15
#define TOWERTEXTURE_CYANIDE 16
#define TOWERTEXTURE_ETHANOL 17
#define TOWERTEXTURE_HYDROCHLORICACID 18
#define TOWERTEXTURE_METHANE 19
#define TOWERTEXTURE_NITRICACID 20
#define TOWERTEXTURE_NITROGLYCERINE 21
#define TOWERTEXTURE_NITROUS 22
#define TOWERTEXTURE_RDX 23
#define TOWERTEXTURE_RUBBER 24
#define TOWERTEXTURE_SALT 25
#define TOWERTEXTURE_SODIUM 26
#define TOWERTEXTURE_TETRODOTOXIN 27
#define TOWERTEXTURE_TNT 28
#define TOWERTEXTURE_TYLENOL 29
#define TOWERTEXTURE_VALIUM 30
#define TOWERTEXTURE_VITAMINC 31
#define TOWERTEXTURE_SECTIONEND 99

#define COLORTEXTURE_SECTIONSTART 100
#define COLORTEXTURE_GRAY 100
#define COLORTEXTURE_BROWN 101
#define COLORTEXTURE_PURPLE 102
#define COLORTEXTURE_CLEAR 103
#define COLORTEXTURE_SECTIONEND 199

#define UITEXTURE_SECTIONSTART 200
#define UITEXTURE_REDX 200
#define UITEXTURE_TOWERMANAGERBACKGROUND 201
#define UITEXTURE_TOWERMANAGERUPGRADEUP 202
#define UITEXTURE_TOWERMANAGERUPGRADEDOWN 203
#define UITEXTURE_TOWERMANAGERDOWNGRADEUP 204
#define UITEXTURE_TOWERMANAGERDOWNGRADEDOWN 205
#define UITEXTURE_MAINMENUBACKGROUND 206
#define UITEXTURE_CHALLENGESBTNUP 207
#define UITEXTURE_CHALLENGESBTNDOWN 208
#define UITEXTURE_CHANGEUSERBTN 209
#define UITEXTURE_EXPLOREBTNUP 210
#define UITEXTURE_EXPLOREBTNDOWN 211
#define UITEXTURE_PLAYBTNUP 212
#define UITEXTURE_PLAYBTNDOWN 213
#define UITEXTURE_RANKINGBTNUP 214
#define UITEXTURE_RANKINGBTNDOWN 215
#define UITEXTURE_PAUSEBTN 216
#define UITEXTURE_MINIMENU 217
#define UITEXTURE_MAINMENUBTN 218
#define UITEXTURE_RESUMEBTN 219
#define UITEXTURE_NEWGAMEBTN 220
#define UITEXTURE_LOGINBACKGROUND 221
#define UITEXTURE_LEVELCLEARBACKGROUND 222
#define UITEXTURE_CONTINUEBTN 223
#define UITEXTURE_SCOREBTN 224
#define UITEXTURE_TIMEBTN 225
#define UITEXTURE_DAMAGEBTN 226
#define UITEXTURE_YOUWINBACKGROUND 227
#define UITEXTURE_YOULOSEBACKGROUND 228
#define UITEXTURE_OVERALLRANKINGBACKGROUND 229
#define UITEXTURE_EXPLORERBACKGROUND 230
#define UITEXTURE_TOWERCARDBACKGROUND 231
#define UITEXTURE_EASYBTN 232
#define UITEXTURE_MEDIUMBTN 233
#define UITEXTURE_HARDBTN 234
#define UITEXTURE_SECTIONEND 299

#define FIELDTEXTURE_SECTIONSTART 300
#define FIELDTEXTURE_BACKGROUND1LR 301
#define FIELDTEXTURE_BACKGROUND1LL 302
#define FIELDTEXTURE_BACKGROUND1UR 303
#define FIELDTEXTURE_BACKGROUND1UL 304
#define FIELDTEXTURE_RANGEINDICATOR 310
#define FIELDTEXTURE_BLEACHTRAP 311
#define FIELDTEXTURE_SECTIONEND 399

#define CREEPTEXTURE_SCTIONSTART 400
#define CREEPTEXTURE_REDARROW 400
#define CREEPTEXTURE_SCTIONEND 499

@interface TextureLibrary : NSObject {
    NSMutableDictionary * library;
}

- (CCTexture2D *) GetTextureWithKey:(int)textureKey;

- (CCTexture2D *) LoadTextureWithName:(NSString *)textureName textureKey:(int)textureKey isPVR:(BOOL)isPVR;
- (CCTexture2D *) GetTowerTextureWithKey:(int)textureKey;
- (CCTexture2D *) GetColorTextureWithKey:(int)textureKey;
- (CCTexture2D *) GetUITextureWithKey:(int)textureKey;
- (CCTexture2D *) GetFieldTextureWithKey:(int)textureKey;
- (CCTexture2D *) GetCreepTextureWithKey:(int)textureKey;

@end
